### ISSUE TITLE
cleanOldJobs (3.x) does not honor $task['cleanupTimeout']

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/cakephp-queue#37]
**2.x**
* https://github.com/Oefenweb/cakephp-queue/blob/3.x/src/Model/Table/QueuedTasksTable.php#L457

**3.x**
* https://github.com/Oefenweb/cakephp-queue/blob/master/Model/QueuedTask.php#L218

**Comment by tersmitten** [comment]
@notpron

**Comment by notpron** [comment]
See PR #38, it includes a fix for default task options overriding the default set by the config file.

**Comment by tersmitten** [comment]
Fixed in #38
